[config]
default_to_workspace = false
min_version = "0.32.9"

[config.modify_core_tasks]
namespace = "core"
private = true

[tasks.format]
dependencies = ["core::format-flow"]
workspace = true

[tasks.lint]
dependencies = ["core::check-format-flow", "core::clippy-flow"]
workspace = true

[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true
