-- Add migration script here
CREATE TABLE IF NOT EXISTS todos (
  id SERIAL PRIMARY KEY,
  body VARCHAR NOT NULL,
  complete BOOLEAN NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
