// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_middleware.ts";
import * as $2 from "./routes/api/auth/refresh.ts";
import * as $3 from "./routes/api/auth/singout.ts";
import * as $4 from "./routes/api/auth/validate.ts";
import * as $5 from "./routes/api/oauth2/github/callback.ts";
import * as $6 from "./routes/api/oauth2/github/index.ts";
import * as $7 from "./routes/api/oauth2/google/callback.ts";
import * as $8 from "./routes/api/oauth2/google/index.ts";
import * as $9 from "./routes/api/register.ts";
import * as $10 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/NavigationBar.tsx";
import * as $$2 from "./islands/TokenValidation.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_middleware.ts": $1,
    "./routes/api/auth/refresh.ts": $2,
    "./routes/api/auth/singout.ts": $3,
    "./routes/api/auth/validate.ts": $4,
    "./routes/api/oauth2/github/callback.ts": $5,
    "./routes/api/oauth2/github/index.ts": $6,
    "./routes/api/oauth2/google/callback.ts": $7,
    "./routes/api/oauth2/google/index.ts": $8,
    "./routes/api/register.ts": $9,
    "./routes/index.tsx": $10,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/NavigationBar.tsx": $$1,
    "./islands/TokenValidation.tsx": $$2,
  },
  baseUrl: import.meta.url,
};

export default manifest;
